#!/usr/bin/env python3
"""Write plain-text copies of the vault's live tables to geo-brain/_exports/.

Run from anywhere:  python3 .claude/scripts/build_exports.py
The live tables (Obsidian Bases) only work inside Obsidian. These Markdown
tables are for AI tools, GitHub and anyone reading the files directly. Files
are only rewritten when their content changes.
"""
import os, re, sys, datetime
try:
    import yaml
except ImportError:
    sys.exit('PyYAML is missing: run "pip install pyyaml" and try again.')

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
OUT = os.path.join(ROOT, 'geo-brain', '_exports')
TODAY = datetime.date.today().isoformat()

def notes(folder, typ):
    base = os.path.join(ROOT, folder)
    for dirpath, _, files in os.walk(base):
        for f in sorted(files):
            if not f.endswith('.md'):
                continue
            text = open(os.path.join(dirpath, f), encoding='utf-8').read()
            m = re.match(r'^---\n(.*?)\n---\n', text, re.S)
            fm = (yaml.safe_load(m.group(1)) or {}) if m else {}
            if fm.get('type') == typ:
                yield fm, text[m.end():] if m else text

def plain(s):
    """Wikilinks to plain text; keep web links; one line; safe inside a table cell."""
    if s is None:
        return ''
    if isinstance(s, list):
        return ', '.join(plain(x) for x in s)
    s = str(s).replace('\\|', '|')
    s = re.sub(r'!\[\[[^\]]*\]\]', '', s)
    s = re.sub(r'\[\[([^\]|]*)\|([^\]]*)\]\]', r'\2', s)
    s = re.sub(r'\[\[([^\]#]*)#([^\]]*)\]\]', lambda m: f'{m.group(1)} ({m.group(2)})' if m.group(1) else m.group(2), s)
    s = re.sub(r'\[\[([^\]]*)\]\]', r'\1', s)
    s = re.sub(r'\s+', ' ', s).strip()
    return s.replace('|', '\\|')

def section(body, heading):
    m = re.search(r'^## ' + re.escape(heading) + r'\s*\n(.*?)(?=^## |^---\s*$|\Z)', body, re.S | re.M)
    return m.group(1).strip() if m else ''

def bullets(text):
    out = {}
    for m in re.finditer(r'^- \*\*(.+?):\*\* (.*)$', text, re.M):
        out[m.group(1)] = m.group(2)
    return out

def table(headers, rows):
    lines = ['| ' + ' | '.join(headers) + ' |', '|' + '---|' * len(headers)]
    lines += ['| ' + ' | '.join(plain(c) for c in r) + ' |' for r in rows]
    return '\n'.join(lines)

def header(title, source, live):
    return (f'# {title}\n\n'
            f'Plain-text copy generated on {TODAY} from the notes in `{source}` by `.claude/scripts/build_exports.py`. '
            f'**Do not edit this file**: change the notes, then run the script again. In Obsidian, the live version is {live}.\n')

def write(name, text):
    path = os.path.join(OUT, name)
    strip = lambda t: re.sub(r'generated on \d{4}-\d{2}-\d{2}', '', t)
    if os.path.exists(path) and strip(open(path, encoding='utf-8').read()) == strip(text):
        return False
    with open(path, 'w', encoding='utf-8') as f:
        f.write(text)
    return True

def by(items, key):
    groups = {}
    for fm, body in items:
        groups.setdefault(fm.get(key) or '(none)', []).append((fm, body))
    return sorted(groups.items())

def export_prompts():
    items = sorted(notes('geo-brain/04-prompt-library/prompts', 'prompt'), key=lambda x: x[0]['id'])
    parts = [header('Prompts (export)', 'geo-brain/04-prompt-library/prompts', 'the Prompt library page and Prompts.base')]
    for group, rows in by(items, 'group'):
        parts.append(f'## {group}\n')
        parts.append(table(['#', 'Prompt', 'Stage', 'Persona', 'Trade', 'Intent', 'Priority', 'Quotr page that should answer it', 'Tested / seen', 'T#'],
            [[fm['id'], fm['prompt'], fm.get('stage'), fm.get('persona'), fm.get('trade'), fm.get('intent'), fm.get('priority'),
              section(b, 'Quotr page that should answer it'), section(b, 'Tested or seen'), fm.get('tracking_id')] for fm, b in rows]) + '\n')
    tracked = sorted([x for x in items if x[0].get('tracking')], key=lambda x: x[0]['tracking_id'])
    track = [header('Tracking set (export)', 'geo-brain/04-prompt-library/prompts', 'the Tracking set page')]
    for grp, label in (('core', 'Core 40'), ('extension', 'Extension 13')):
        rows = []
        for fm, b in tracked:
            if fm.get('tracking_group') != grp:
                continue
            t = bullets(section(b, 'Monthly tracking'))
            rows.append([fm['tracking_id'], fm.get('test_id'), fm['id'], fm['prompt'], fm.get('stage'), fm.get('persona'), fm.get('tier'),
                         t.get('September 2026 baseline (Perplexity)'), t.get('Named in the answer, or what to watch for')])
        track.append(f'## {label}\n')
        track.append(table(['T#', 'Test ID', 'Library ID', 'Prompt (verbatim)', 'Stage', 'Persona', 'Tier', 'Sept 2026 baseline (Perplexity)',
                            'Named in answer / watch for'], rows) + '\n')
    return [('Prompts (export).md', '\n'.join(parts)), ('Tracking set (export).md', '\n'.join(track))]

def export_tests():
    items = sorted(notes('geo-brain/07-measurement/test-runs', 'test-run'), key=lambda x: (str(x[0].get('date')), x[0].get('seq') or 0))
    parts = [header('AI test runs (export)', 'geo-brain/07-measurement/test-runs', 'Test runs.base and the AI visibility baseline page')]
    for test_set, rows in by(items, 'test_set'):
        parts.append(f'## {test_set}\n')
        parts.append(table(['Date', 'Engine', 'Test', 'Prompt ID', 'Prompt (as run)', 'Quotr named', 'Position', 'quotr.ai in sources', 'Result', 'Fact-check re-run'],
            [[fm.get('date'), fm.get('engine'), fm.get('test_id'), fm.get('prompt_note'), fm.get('prompt'),
              {True: 'Yes', False: 'No'}.get(fm.get('quotr_named'), '—'), fm.get('position'), fm.get('quotr_sources'),
              fm.get('result_summary'), fm.get('fact_check')] for fm, b in rows]) + '\n')
    return [('AI test runs (export).md', '\n'.join(parts))]

def export_roadmap():
    items = sorted(notes('geo-brain/05-content-strategy/roadmap', 'roadmap-item'), key=lambda x: x[0]['id'])
    parts = [header('Content roadmap (export)', 'geo-brain/05-content-strategy/roadmap', 'the Content roadmap page and Content roadmap.base')]
    for cluster, rows in by(items, 'cluster'):
        parts.append(f'## Cluster {cluster}\n')
        parts.append(table(['ID', 'Working title', 'Format', 'Target prompts', 'Funnel', 'Persona / trade', 'Unique Quotr data or angle', 'Priority', 'Month', 'Status', 'Owner'],
            [[fm['id'], fm.get('title'), fm.get('format'), fm.get('target_prompts'), fm.get('funnel'),
              plain(fm.get('persona')) + (' / ' + plain(fm.get('trade')) if fm.get('trade') else ''),
              section(b, 'Unique Quotr data or angle'), fm.get('priority'), fm.get('timing') or fm.get('month'), fm.get('status'), fm.get('owner')]
             for fm, b in rows]) + '\n')
    return [('Content roadmap (export).md', '\n'.join(parts))]

def export_tasks():
    items = sorted(notes('geo-brain/08-action-plan/tasks', 'task'), key=lambda x: x[0].get('rank') or 999)
    parts = [header('30-60-90 tasks (export)', 'geo-brain/08-action-plan/tasks', 'the 30-60-90 plan page and Tasks.base')]
    phases = {}
    for fm, b in items:
        phases.setdefault(fm.get('phase'), []).append((fm, b))
    for phase, rows in phases.items():
        parts.append(f'## {phase}\n')
        parts.append(table(['ID', 'Task', 'Owner (suggested)', 'Effort', 'Impact', 'Depends on', 'Status', 'Done when'],
            [[fm['id'], fm.get('task'), fm.get('owner'), fm.get('effort'), fm.get('impact'), fm.get('depends_on_text'), fm.get('status'), fm.get('done_when')]
             for fm, b in rows]) + '\n')
    parts.append('## Task details\n')
    for fm, b in items:
        body = re.split(r'^---\s*$', b, flags=re.M)[0].strip()
        body = re.sub(r'\[\[([^\]|]*)\|([^\]]*)\]\]', r'\2', body)
        body = re.sub(r'\[\[([^\]#]*)#([^\]]*)\]\]', lambda m: f'{m.group(1)} ({m.group(2)})', body)
        body = re.sub(r'\[\[([^\]]*)\]\]', r'\1', body)
        parts.append(re.sub(r'^# ', '### ', body) + f'\n\n*Status: {fm.get("status")}.*\n')
    return [('30-60-90 tasks (export).md', '\n'.join(parts))]

def export_questions():
    items = sorted(notes('geo-brain/00-quotr/open-questions', 'question'), key=lambda x: x[0]['id'])
    parts = [header('Open questions (export)', 'geo-brain/00-quotr/open-questions', 'Open questions.base and the QA log page')]
    for topic, rows in by(items, 'topic'):
        parts.append(f'## {topic}\n')
        parts.append(table(['ID', 'Question', 'Ask', 'Status', 'Answer', 'Answered on'],
            [[fm['id'], fm.get('question'), fm.get('ask'), fm.get('status'), fm.get('answer'), fm.get('answered_on')] for fm, b in rows]) + '\n')
    return [('Open questions (export).md', '\n'.join(parts))]

def main():
    os.makedirs(OUT, exist_ok=True)
    changed = 0
    for fn in (export_prompts, export_tests, export_roadmap, export_tasks, export_questions):
        for name, text in fn():
            changed += write(name, text)
    print(f'Exports in geo-brain/_exports: {changed} file{"s" if changed != 1 else ""} updated')

if __name__ == '__main__':
    main()
